// Code generated by mockery. DO NOT EDIT.

package spider

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	spider "webcrawler/pkg/generated/service/spider"
)

// MockSpiderClient is an autogenerated mock type for the SpiderClient type
type MockSpiderClient struct {
	mock.Mock
}

type MockSpiderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpiderClient) EXPECT() *MockSpiderClient_Expecter {
	return &MockSpiderClient_Expecter{mock: &_m.Mock}
}

// GetHealth provides a mock function with given fields: ctx, in, opts
func (_m *MockSpiderClient) GetHealth(ctx context.Context, in *spider.HealthRequest, opts ...grpc.CallOption) (*spider.HealthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 *spider.HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *spider.HealthRequest, ...grpc.CallOption) (*spider.HealthResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *spider.HealthRequest, ...grpc.CallOption) *spider.HealthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spider.HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *spider.HealthRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpiderClient_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type MockSpiderClient_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
//   - ctx context.Context
//   - in *spider.HealthRequest
//   - opts ...grpc.CallOption
func (_e *MockSpiderClient_Expecter) GetHealth(ctx interface{}, in interface{}, opts ...interface{}) *MockSpiderClient_GetHealth_Call {
	return &MockSpiderClient_GetHealth_Call{Call: _e.mock.On("GetHealth",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSpiderClient_GetHealth_Call) Run(run func(ctx context.Context, in *spider.HealthRequest, opts ...grpc.CallOption)) *MockSpiderClient_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*spider.HealthRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockSpiderClient_GetHealth_Call) Return(_a0 *spider.HealthResponse, _a1 error) *MockSpiderClient_GetHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpiderClient_GetHealth_Call) RunAndReturn(run func(context.Context, *spider.HealthRequest, ...grpc.CallOption) (*spider.HealthResponse, error)) *MockSpiderClient_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeenList provides a mock function with given fields: ctx, opts
func (_m *MockSpiderClient) GetSeenList(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSeenList")
	}

	var r0 grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpiderClient_GetSeenList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeenList'
type MockSpiderClient_GetSeenList_Call struct {
	*mock.Call
}

// GetSeenList is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockSpiderClient_Expecter) GetSeenList(ctx interface{}, opts ...interface{}) *MockSpiderClient_GetSeenList_Call {
	return &MockSpiderClient_GetSeenList_Call{Call: _e.mock.On("GetSeenList",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockSpiderClient_GetSeenList_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockSpiderClient_GetSeenList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockSpiderClient_GetSeenList_Call) Return(_a0 grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse], _a1 error) *MockSpiderClient_GetSeenList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpiderClient_GetSeenList_Call) RunAndReturn(run func(context.Context, ...grpc.CallOption) (grpc.BidiStreamingClient[spider.SeenListRequest, spider.SeenListResponse], error)) *MockSpiderClient_GetSeenList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpiderClient creates a new instance of MockSpiderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpiderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpiderClient {
	mock := &MockSpiderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
