// Code generated by mockery. DO NOT EDIT.

package spider

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	spider "webcrawler/pkg/generated/service/spider"
)

// MockSpiderServer is an autogenerated mock type for the SpiderServer type
type MockSpiderServer struct {
	mock.Mock
}

type MockSpiderServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpiderServer) EXPECT() *MockSpiderServer_Expecter {
	return &MockSpiderServer_Expecter{mock: &_m.Mock}
}

// GetHealth provides a mock function with given fields: _a0, _a1
func (_m *MockSpiderServer) GetHealth(_a0 context.Context, _a1 *spider.HealthRequest) (*spider.HealthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 *spider.HealthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *spider.HealthRequest) (*spider.HealthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *spider.HealthRequest) *spider.HealthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spider.HealthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *spider.HealthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSpiderServer_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type MockSpiderServer_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *spider.HealthRequest
func (_e *MockSpiderServer_Expecter) GetHealth(_a0 interface{}, _a1 interface{}) *MockSpiderServer_GetHealth_Call {
	return &MockSpiderServer_GetHealth_Call{Call: _e.mock.On("GetHealth", _a0, _a1)}
}

func (_c *MockSpiderServer_GetHealth_Call) Run(run func(_a0 context.Context, _a1 *spider.HealthRequest)) *MockSpiderServer_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*spider.HealthRequest))
	})
	return _c
}

func (_c *MockSpiderServer_GetHealth_Call) Return(_a0 *spider.HealthResponse, _a1 error) *MockSpiderServer_GetHealth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSpiderServer_GetHealth_Call) RunAndReturn(run func(context.Context, *spider.HealthRequest) (*spider.HealthResponse, error)) *MockSpiderServer_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeenList provides a mock function with given fields: _a0
func (_m *MockSpiderServer) GetSeenList(_a0 grpc.BidiStreamingServer[spider.SeenListRequest, spider.SeenListResponse]) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetSeenList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(grpc.BidiStreamingServer[spider.SeenListRequest, spider.SeenListResponse]) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSpiderServer_GetSeenList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeenList'
type MockSpiderServer_GetSeenList_Call struct {
	*mock.Call
}

// GetSeenList is a helper method to define mock.On call
//   - _a0 grpc.BidiStreamingServer[spider.SeenListRequest,spider.SeenListResponse]
func (_e *MockSpiderServer_Expecter) GetSeenList(_a0 interface{}) *MockSpiderServer_GetSeenList_Call {
	return &MockSpiderServer_GetSeenList_Call{Call: _e.mock.On("GetSeenList", _a0)}
}

func (_c *MockSpiderServer_GetSeenList_Call) Run(run func(_a0 grpc.BidiStreamingServer[spider.SeenListRequest, spider.SeenListResponse])) *MockSpiderServer_GetSeenList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(grpc.BidiStreamingServer[spider.SeenListRequest, spider.SeenListResponse]))
	})
	return _c
}

func (_c *MockSpiderServer_GetSeenList_Call) Return(_a0 error) *MockSpiderServer_GetSeenList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSpiderServer_GetSeenList_Call) RunAndReturn(run func(grpc.BidiStreamingServer[spider.SeenListRequest, spider.SeenListResponse]) error) *MockSpiderServer_GetSeenList_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedSpiderServer provides a mock function with no fields
func (_m *MockSpiderServer) mustEmbedUnimplementedSpiderServer() {
	_m.Called()
}

// MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSpiderServer'
type MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSpiderServer is a helper method to define mock.On call
func (_e *MockSpiderServer_Expecter) mustEmbedUnimplementedSpiderServer() *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call {
	return &MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSpiderServer")}
}

func (_c *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call) Run(run func()) *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call) Return() *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call) RunAndReturn(run func()) *MockSpiderServer_mustEmbedUnimplementedSpiderServer_Call {
	_c.Run(run)
	return _c
}

// NewMockSpiderServer creates a new instance of MockSpiderServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpiderServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpiderServer {
	mock := &MockSpiderServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
