// Code generated by mockery. DO NOT EDIT.

package searcher

import (
	context "context"
	searcher "webcrawler/pkg/generated/service/searcher"

	mock "github.com/stretchr/testify/mock"
)

// MockSearcherServer is an autogenerated mock type for the SearcherServer type
type MockSearcherServer struct {
	mock.Mock
}

type MockSearcherServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearcherServer) EXPECT() *MockSearcherServer_Expecter {
	return &MockSearcherServer_Expecter{mock: &_m.Mock}
}

// SearchPages provides a mock function with given fields: _a0, _a1
func (_m *MockSearcherServer) SearchPages(_a0 context.Context, _a1 *searcher.SearchRequest) (*searcher.SearchResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SearchPages")
	}

	var r0 *searcher.SearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *searcher.SearchRequest) (*searcher.SearchResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *searcher.SearchRequest) *searcher.SearchResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*searcher.SearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *searcher.SearchRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearcherServer_SearchPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPages'
type MockSearcherServer_SearchPages_Call struct {
	*mock.Call
}

// SearchPages is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *searcher.SearchRequest
func (_e *MockSearcherServer_Expecter) SearchPages(_a0 interface{}, _a1 interface{}) *MockSearcherServer_SearchPages_Call {
	return &MockSearcherServer_SearchPages_Call{Call: _e.mock.On("SearchPages", _a0, _a1)}
}

func (_c *MockSearcherServer_SearchPages_Call) Run(run func(_a0 context.Context, _a1 *searcher.SearchRequest)) *MockSearcherServer_SearchPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*searcher.SearchRequest))
	})
	return _c
}

func (_c *MockSearcherServer_SearchPages_Call) Return(_a0 *searcher.SearchResponse, _a1 error) *MockSearcherServer_SearchPages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearcherServer_SearchPages_Call) RunAndReturn(run func(context.Context, *searcher.SearchRequest) (*searcher.SearchResponse, error)) *MockSearcherServer_SearchPages_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedSearcherServer provides a mock function with no fields
func (_m *MockSearcherServer) mustEmbedUnimplementedSearcherServer() {
	_m.Called()
}

// MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSearcherServer'
type MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSearcherServer is a helper method to define mock.On call
func (_e *MockSearcherServer_Expecter) mustEmbedUnimplementedSearcherServer() *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call {
	return &MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSearcherServer")}
}

func (_c *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call) Run(run func()) *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call) Return() *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call) RunAndReturn(run func()) *MockSearcherServer_mustEmbedUnimplementedSearcherServer_Call {
	_c.Run(run)
	return _c
}

// NewMockSearcherServer creates a new instance of MockSearcherServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearcherServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcherServer {
	mock := &MockSearcherServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
