// Code generated by mockery. DO NOT EDIT.

package searcher

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	searcher "webcrawler/pkg/generated/service/searcher"
)

// MockSearcherClient is an autogenerated mock type for the SearcherClient type
type MockSearcherClient struct {
	mock.Mock
}

type MockSearcherClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearcherClient) EXPECT() *MockSearcherClient_Expecter {
	return &MockSearcherClient_Expecter{mock: &_m.Mock}
}

// SearchPages provides a mock function with given fields: ctx, in, opts
func (_m *MockSearcherClient) SearchPages(ctx context.Context, in *searcher.SearchRequest, opts ...grpc.CallOption) (*searcher.SearchResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SearchPages")
	}

	var r0 *searcher.SearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *searcher.SearchRequest, ...grpc.CallOption) (*searcher.SearchResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *searcher.SearchRequest, ...grpc.CallOption) *searcher.SearchResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*searcher.SearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *searcher.SearchRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearcherClient_SearchPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPages'
type MockSearcherClient_SearchPages_Call struct {
	*mock.Call
}

// SearchPages is a helper method to define mock.On call
//   - ctx context.Context
//   - in *searcher.SearchRequest
//   - opts ...grpc.CallOption
func (_e *MockSearcherClient_Expecter) SearchPages(ctx interface{}, in interface{}, opts ...interface{}) *MockSearcherClient_SearchPages_Call {
	return &MockSearcherClient_SearchPages_Call{Call: _e.mock.On("SearchPages",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSearcherClient_SearchPages_Call) Run(run func(ctx context.Context, in *searcher.SearchRequest, opts ...grpc.CallOption)) *MockSearcherClient_SearchPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*searcher.SearchRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockSearcherClient_SearchPages_Call) Return(_a0 *searcher.SearchResponse, _a1 error) *MockSearcherClient_SearchPages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearcherClient_SearchPages_Call) RunAndReturn(run func(context.Context, *searcher.SearchRequest, ...grpc.CallOption) (*searcher.SearchResponse, error)) *MockSearcherClient_SearchPages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearcherClient creates a new instance of MockSearcherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearcherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcherClient {
	mock := &MockSearcherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
